AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  alexa itteq
  今日イッテQがあるか答えるAlexaスキル

Parameters:
  Region:
    Type: String
  Bucket:
    Type: String
  Key:
    Type: String

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs16.x
    CodeUri: dist/

Resources:
  AlexaItteqFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: alexa.handler
      Events:
        Alexa:
          Type: AlexaSkill
        Scheduled:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Environment:
        Variables:
          REGION:
            Ref: Region
          BUCKET:
            Ref: Bucket
          KEY:
            Ref: Key
