AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  alexa itteq
  今日イッテQがあるか答えるAlexaスキル

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs12.x
    CodeUri: dist/

Resources:
  AlexaItteqFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: alexa.handler
      Events:
        Alexa:
          Type: AlexaSkill
        Scheduled:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Environment:
        Variables:
          REGION: region
          BUCKET: bucket
          KEY: key
  PrefetchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: prefetch.handler
      Events:
        PrefetchEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
      Environment:
        Variables:
          REGION: region
          BUCKET: bucket
          KEY: key
