name: build-and-deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master    
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Versions
        run: |
          sam_cli_version=`grep aws-sam-cli .tool-versions | awk '{print $2}'`
          echo "SAM_CLI_VERSION=${sam_cli_version}" >> $GITHUB_ENV
          nodejs_version=`grep nodejs .tool-versions | awk '{print $2}'`
          echo "NODEJS_VERSION=${nodejs_version}" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version:  ${{ env.NODEJS_VERSION }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Install sam-cli
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          version: ${{ env.SAM_CLI_VERSION }}
      - name: Build
        run: yarn build
      - name: Configure AWS Credentials
        if: startsWith(github.ref, 'refs/heads/master')
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-duration-seconds: 1200
          role-session-name: AlexaItteq
      - name: Deploy
        if: startsWith(github.ref, 'refs/heads/master')
        run: sam deploy --stack-name alexa-itteq --resolve-s3 --capabilities CAPABILITY_IAM --parameter-overrides "Region=${{ secrets.REGION }} Bucket=${{ secrets.BUCKET }} Key=${{ secrets.KEY }}" --no-fail-on-empty-changeset --no-confirm-changeset
